name: l10n_example
description: A minimal example of a localized Flutter app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  intl_translation: ^0.18.2

# dev_dependencies:
  # example_utils:
  #   path: ../../example_utils

flutter:
  uses-material-design: true
