name: gen_l10n_example
publish_to: none
description: >-
  Example of an internationalized Flutter app that uses `flutter gen-l10n`.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.6

# #docregion FlutterLocalizations
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
# #enddocregion FlutterLocalizations

# dev_dependencies:
#   example_utils:
#     path: ../../example_utils

# #docregion Generate
# The following section is specific to Flutter.
flutter:
  generate: true # Add this line
# #enddocregion Generate
  uses-material-design: true
